### ISSUE TITLE
New reform broke openfisca_france_data ?

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france-data#102]
Recent changes of reform in openfisca_france seams to make the run of openfisca-france-data impossible. 
```
File "test_aggregates.py", line 26, in <module>
    from openfisca_france_data.input_data_builders import get_input_data_frame
  File "/Users/adrienpacifico/openfisca/openfisca-france-data/openfisca_france_data/__init__.py", line 29, in <module>
    from .model.base import TaxBenefitSystem
  File "/Users/adrienpacifico/openfisca/openfisca-france-data/openfisca_france_data/model/base.py", line 61, in <module>
    reference = openfisca_france_tax_benefit_system,
TypeError: make_reform() takes at least 3 arguments (2 given)
```

I think the new fsolve function is the problem.

@cbenz am I off track ?

**Comment by adrienpacifico** [comment]
Sorry to all of you, looks like that I mixed all my branches...

**Comment by adrienpacifico** [comment]
On openfisca-france/next : last commit
On openfisca-france-data/dev : last commit
On openfica-survey-manager/dev : last commit
On openfisca-plugin-agregates/master : (last master commit)

Everything works fine with openfisca-core ( e.g 87270f4243ac27a9d53f3378481b8ab82b29c286) , 
till commit : c9f51f1589136e76d8523a8bd7cab1400825e368 (4/09/2015) where I get the above error trace.

**Comment by cbenz** [comment]
2c708d9f45730dd53c511797281e30bf0afbad36 fixed the problem.

@adrienpacifico please confirm & close issue

**Comment by adrienpacifico** [comment]
I will, some issue for now but master branch might be too old, I'll implement your change in newer branches. I'll come back ASAP.

**Comment by cbenz** [comment]
I merged master in dev branch

**Comment by adrienpacifico** [comment]
Thanx, looks like it works fine @home.

I don't think that I can close the issue, but it is closed for me ( @benjello can you check it's ok for you too ? ).

**Comment by benjello** [comment]
I will tonight. Ping me back tomorrow if i don't

**Comment by adrienpacifico** [comment]
Ping ?

**Comment by benjello** [comment]
This week-end hopefully

**Comment by adrienpacifico** [comment]
Ping, still looks ok for me.
