### ISSUE TITLE
Dependance inutile entre of-france et of-france-data

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france-data#107]
Il me semble que les import réalisé dans [/tests/base.py](https://github.com/openfisca/openfisca-france-data/blob/master/openfisca_france_data/tests/base.py#L29-L38) sont inutiles et entrainent une dépendance non nécessaire entre les deux repo.

Je n'ai pas trop compris à quoi servent ces imports et l'utilité de créer tout les reform_tax_benefit_system à chaque fois qu'on fait tourner france-data (si c'est pour gagner du temps sur les travis build, est-ce vraiment nécessaire ?).

Il doit sûrement y avoir un moyen d'automatiser tout cela sans que les réformes de france soient "hard-coded" dans france-data.

**Comment by benjello** [comment]
openfisca-france et openfisca-france-data devront forcément dépendre l'un de l'autre l'un étant une extension du premier.
Après la gestion des réformes si tu as plus simple et plus propre, je suis preneur une fois validé par le maître jedi @cbenz .

**Comment by adrienpacifico** [comment]
Il existe une liste de réforme dans le repo openfisca-france ; recoder la liste des réformes à la main dans france-data me semble redondant (et donc dispensable ? ).

Si ces imports (qui une fois commenté permettent de faire tourner le code) servent uniquement à faire tourner les tests_yaml, je pense qu'ils impliquent une perte de performance pour l'utilisateur qui veut lancer uniquement sa réforme (puisqu'il charge toutes les réformes en cache dès qu'on veut faire tourner france-data).

Ensuite il doit surement y avoir un meilleur moyen avec pkg_utils ou autre, qu'en dit maître @cbenz ?

**Comment by cbenz** [comment]
> Il me semble que les import réalisé dans /tests/base.py sont inutiles et entrainent une dépendance non nécessaire entre les deux repo.

Les imports sont utiles car ils permettent de [construire les réformes](https://github.com/openfisca/openfisca-france-data/blob/3a70f59bdb51fcd9f9e5c2047e839e8e196bf079/openfisca_france_data/tests/base.py#L60-L70) une fois pour toutes pour tous les tests.

**Comment by cbenz** [comment]
@adrienpacifico Je vais essayer de m'imprégner correctement de ta question car pour l'instant je ne saisis pas bien. Je te recontacte

**Comment by benjello** [comment]
Je pense que ce problème est obsolète. Je ferme.
@adrienpacifico rouvre s'il le faut.
