### ISSUE TITLE
Improve travis config

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-data#109]
https://travis-ci.org/benjello/openfisca-france-data/builds/104065217 fails partly because it can access
a recent pandas version.
Related to https://github.com/openfisca/openfisca-france-indirect-taxation/issues/106#issuecomment-173875081

**Comment by adrienpacifico** [comment]
I didn't see that issue, pandas has changed it's behavior since 0.17 .

Changes are listed [here](http://pandas.pydata.org/pandas-docs/version/0.17.0/whatsnew.html).

A simple pip install `$ pip install pandas==0.16.2` at the beginning to the travis build fix the issue.

**Comment by benjello** [comment]
But i do not know what changes caused you trouble.
The problem with travis is that it cannot use pandas 0.17.

**Comment by benjello** [comment]
Sûrement résolu.
