### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-data#110]
Take https://github.com/openfisca/openfisca-france/pull/379#event-530014330 into account.

**Comment by benjello** [comment]
@adrienpacifico you may be interested in looking into this too.

**Comment by adrienpacifico** [comment]
Okidocki

**Comment by benjello** [comment]
Do you want to try to merge it with openfisca-france-data ? Or do you prefer that I look intot it ?

**Comment by adrienpacifico** [comment]
I prefer if you take care of it (I'm late on many things...).

**Comment by benjello** [comment]
Closed by #111
