### ISSUE TITLE
logging level might not be adapted.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france-data#112]
Hello Mahdi,

L'ensemble des log.\* sont des log.info, je pense qu'il faudrait peut être hiérarchiser leurs niveaux (ça s'applique aussi à survey_manager, etc).

Quand on lance les build_aggregates par exemple, on a énormément/trop d'information. 

Je pense qu'il faudrait faire passer une grande partie de ceux-ci en log.debug car elles ne sont interessante que si on cherche à améliorer le programme (e.g     

```
log.info(    # From 471 variables, we keep 414 eligibles variables
        u"From {} variables, we keep {} eligibles variables".format(
            len(set().union(*vars_sets)),
            len(eligible_vars),
            )
        )
```

Une partie devrait rester en log.info (affiché quand exécuté depuis la console), comme par exemple l'information sur le step en cours d'exécution ( e.g `log.info("05_foyer: extraction des données foyer")` )

D'autres devrait être mise en log.warn , car c'est le niveau minimum affiché par défaut des les notebooks.

Par exemple dans Survey_scenatio/scenarios.py  :

```

def create_data_frame_by_entity_key_plural(self, variables = None, indices = False, roles = False):
    [...]
    if missing_variables:
                log.info("These variables aren't par of the tax-benefit system: {}".format(missing_variables))
    [...]
```

ne sera pas affiché à un utilisateur que l'utilise sous un notebook. Un log.warn me semble plus adapté.

Je pense modifier des niveaux de log, c'est juste pour avoir ton opinion avant de me lancer dedans si jamais tu n'es pas d'accord.

**Comment by benjello** [comment]
Complètement d'accord

**Comment by benjello** [comment]
Seems outdated
