### ISSUE TITLE
Improve testing, tagging and packaging

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-data#120]
We adopt the strategy used on openfisca-core and openfisca-france.
After a successful first PR, the tests always fail for #119  !
@fpagnoux @cbenz : any hint ?

**Comment by benjello** [comment]
[Same here on another repo](https://travis-ci.org/openfisca/openfisca-survey-manager/builds/178904804) :-(

**Comment by benjello** [comment]
@fpagnoux : I badly need you here ;-)

**Comment by fpagnoux** [comment]
Looking at ti

**Comment by benjello** [comment]
Fixed
