### ISSUE TITLE
F7EA/ecpess (réduction d'impôt pour enfants à charge poursuivants leurs études)

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-france-data#130]
Bonjour à tous,

Les cases F7EA à F7EG donnent droit à une réduction d'impôt pour chaque enfant de 60 à 180 euros.
La formule de calcul impliquée est ecpess, qui fonctionne bien dans la dernière version d'OpenFIsca ( `Version: 18.11.0`) 

Je n'ai pas l'impression que ce soit pris en compte dans les simulations, je me trompe ?

Avec plus de 60% des logements fiscaux ayant des enfants, l'impact de la réduction d'impôt peut être conséquent, non ?

C'est peut être déjà pris en compte par une autre variable ?

Les variables _7EA à  G sont bien présente dans l'ERFS.

**Comment by benjello** [comment]
Bonjour @adrienpacifico,

 Quand tu dis pas pris en compte dans les simulations, as-tu essayé de faire tourner un test ?
Merci !

**Comment by benjello** [comment]
Argh: je me rends compte que tu es sur france-data !
Faut m'en dire plus ! Quel survey-scenario tu utilises etc ?

**Comment by adrienpacifico** [comment]
@benjello hello,

ERFS, je questionne essentiellement `openfisca_france_data/erfs/input_data_builder` .

Je n'ai pas fait tourner de test, mais un git grep et un search sur le repo GitHub ne m'ont fait sortir aucune occurence sur f7ea (à l'exception d'un vieux bout code de TAXIPP je pense). Rien pour ecpess, etc.

D'ailleurs oublié ce détail (remplir la case f7ea) dans la note de l'IDEP 😰

**Comment by benjello** [comment]
Ok on va regarder ...

**Comment by benjello** [comment]
Too old. Je ferme.
