### ISSUE TITLE
Erreur de openfisca_france_data.erfs_fpr.get_survey_scenario avec l'erfs-fpr 2015

### ISSUE THREAD

**Issue by FrancoisTeyssier** [openfisca/openfisca-france-data#194]
**Contexte :** J'essaie de faire des simulations sur les erfs-fpr 2015, 2016 et 2017. Les erfs ont changé en 2015 et ne peuvent pas être gérées par openfisca_france_data\erfs_fpr\input_data_builder sans modifications: elles sont en csv au lieu d'être en dta (Stata), et une variable ("noiper") appelée par les fichiers d'input_data_builder a disparu des erfs. 

J'ai commencé par convertir les erfs-fpr en dta avec le code [csv_to_stata.txt](https://github.com/openfisca/openfisca-france-data/files/6284993/csv_to_stata.txt) ci-joint.

J'ai modifié openfisca_france_data\erfs_fpr\input_data_builder pour être compatible avec l'erfs-fpr 2015 (suppression de la mention de la variable "noiper", gestion manuelle de deux erreurs sur un ménage et une famille). Cela est fait dans la branche remotes/origin/memoire_Francois_TdO de open-fisca-france-data.

J'utilise les version suivantes :

-open-fisca-core (35.0.4)
-open-fisca-france (48.15.1)
-open-fisca-france-data (memoire_Francois_TdO)
-openfisca-survey-manager (0.39.1)
-taxipp (ppa_biactif)

**Bug :** Le code [first_tests.txt](https://github.com/openfisca/openfisca-france-data/files/6285159/first_tests.txt) ci-joint fonctionne bien avec la configuration citée ci-dessus pour l'erfs-fpr 2014, mais pas avec l'erfs-fpr 2015. Les étapes build_collection.py de openfisca-survey-manager et input_data_builder/\_\_init\_\_.py de openfisca-france-data se déroulent sans accroc. L'erreur apparaît au moment de lancer 
`get_survey_scenario(
    tax_benefit_system = tax_benefit_system,
    year = 2015,
    rebuild_input_data = True,
    )`

On obtiens l'erreur suivante : **"Inconsistent input: variable heures_remunerees_volume has already been set for all months contained in period 2013, and value [0. 0. 0. ... 0. 0. 0.] provided for 2013 doesn't match the total ([0. 0. 0. ... 0. 0. 0.]). This error may also be thrown if you try to call set_input twice for the same variable and period."**

**Question :** A quoi pourrait être due cette erreur et de quel côté chercher la solution ? Il me semble que la variable "heures_remunerees_volume" est créée dans le fichier openfisca_france_data\erfs_fpr\input_data_builder\step_03_variables_individuelles.py que je n'ai pas modifié. 

Merci beaucoup si vous trouvez un peu de temps pour m'aider !
@benjello @claireleroy

**Comment by benjello** [comment]
@FrancoisTeyssier j'ai quelques requêtes pour toi sur le slack openfisca.

**Comment by claireleroy** [comment]
@FrancoisTeyssier Je suis entrain de regarder ton code. Premier (micro) commentaire : le mieux c'est de versionner l'intégralité de ton code comme ça on y a accès facilement, ce qui inclue ton script `first_tests`. Concrètement, il faudrait que tu commit ce script dans TAXIPP sur ta branche `ppa_biactif`. Tu peux le mettre dans le dossier `tests` de TAXIPP par exemple. 

(NB : Ce n'est pas grave si le code est brouillon, c'est le but de ta branche que d'être ton brouillon)

**Comment by claireleroy** [comment]
@FrancoisTeyssier Salut François, je n'ai pas très bien compris d'où venait le problème mais en gros le code n'avait pas l'air d'apprécié de devoir passer 2 fois dans [surveys.py](https://github.com/openfisca/openfisca-france-data/blob/master/openfisca_france_data/surveys.py) lignes 155 à 177 :
```
for offset in [-1, -2]:
            for variable in three_year_span_variables:
                assert variable in self.used_as_input_variables, \
                    f"{variable} is not a in the input_varaibles to be used {self.used_as_input_variables}"  # noqa: E501

                if self.baseline_tax_benefit_system.variables[variable].value_type == Enum:
                    simulation.set_input(
                        variable,
                        simulation_period.offset(offset),
                        simulation.calculate(
                            variable,
                            period = periods.period(self.year).first_month,
                            )
                        )
                else:
                    simulation.set_input(
                        variable,
                        simulation_period.offset(offset),
                        simulation.calculate_add(
                            variable,
                            period = self.year,
                            ),
                        )
```

Ma solution qui semble marcher : le faire boucler que sur une période, cf. ma branche `ugly-fix-for-francois` sur openfisca-france-data. Je trouve 60,8 milliards d'euros d'IRPP en 2015 avec cette solution. Ce qui semble correct non ? Je te laisse tester et me dire ce que ça donne chez toi.

**Comment by FrancoisTeyssier** [comment]
Merci beaucoup @claireleroy  ! Ça a l'air de fonctionner, je trouve la même somme que toi, c'est 10 milliards en dessous de la réalité mais c'est cohérent avec ce que calcule la fonction sur les années précédentes de l'erfs.

**Comment by claireleroy** [comment]
@FrancoisTeyssier je ferme l'issue alors si c'est bon :)
