### ISSUE TITLE
Une erreur advient lorsqu'on essaie de travailler avec plusieurs années à la fois

### ISSUE THREAD

**Issue by bchoho** [openfisca/openfisca-france-data#196]
Bonjour! Je suis stagiaire au Crest et je suis souhaite utiliser OpenFisca avec le modèle TaxIPP pour faire de la microsimulation avec les données ERFS/FPR.

## Ce que j'ai fait et le résultat

J'ai build l'année 2014 puis j'ai lancé le code ci-dessous pour 2014, sans erreur. J'ai ensuite build 2015 sans erreur. C'est lorsque j'ai voulu lancé le code ci-dessous en changeant l'année à 2015 (3 emplacements) ainsi que dans "INSERT PATH/openfisca-france-data/openfisca_france_data/erfs_fpr/input_data_builder/__init__.py" (1 emplacement) que j'ai eu l'erreur suivante:

AssertionError

## Tests

-J'ai également fait les mêmes étapes avec l'option rebuild_input_data = True dans le code ci-dessous, avec la même erreur.

-Lancer une année sans la build donne l'erreur suivante:
NoOptionError: No option 'erfs_fpr' in section: 'collections'

-Réessayer de lancer 2014 lorsque l'on a déjà build 2015 donne l'erreur suivante:
AssertionError: Survey erfs_fpr_2014 cannot be found for survey collection erfs_fpr.
    Available surveys are :['erfs_fpr_2015']

-Après avoir build 2015, si l'on build 2014 à nouveau et on essaie de lancer le code, cela fonctionne sans erreur

### En adaptant le chemin d'accès
cd "INSERT PATH/openfisca-survey-manager/openfisca_survey_manager/scripts"
python build_collection.py -c erfs_fpr -d -m -s 2014

## Le code

from openfisca_france_data import france_data_tax_benefit_system
from openfisca_france_data.erfs_fpr.get_survey_scenario import get_survey_scenario
import sys

sys.argv = ['-y 2014']

### En adaptant le chemin d'accès
exec(open("INSERT PATH/openfisca-france-data/openfisca_france_data/erfs_fpr/input_data_builder/__init__.py").read())

tax_benefit_system = france_data_tax_benefit_system

survey_scenario = get_survey_scenario(
    tax_benefit_system = tax_benefit_system,
    year = 2014,
    rebuild_input_data = False
    )

survey_scenario.compute_aggregate(variable = 'irpp', period = 2014)

**Comment by bchoho** [comment]
@claireleroy @benjello

**Comment by benjello** [comment]
Faire 
```
python build_collection.py -c erfs_fpr -d -m
 ```

une seule fois pour construire tous les h5 des données erf-fpr pour toutes les années présentes. Et ne plus le refaire.
l'option -m efface les méta données (je crois).

**Comment by claireleroy** [comment]
@benjello Merci ! On a l'impression que ça a marché et qu'on a atteint une erreur plus en aval désormais.
