### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-data#198]
Hi there!

I really enjoy OpenFisca-France-Data, but I recently encountered an issue.

### Here is what I did:

I merged a branch

### Here is what I expected to happen:

Tagging and deployment to Pypi

### Here is what actually happened:

An error at [deployment](https://app.circleci.com/pipelines/github/openfisca/openfisca-france-data/338/workflows/fc3da6d0-d409-4a3e-bba4-8cab759c8a13/jobs/803) mentionning a key problem.

## Context

I identify more as a:

- Economist _(I make microsimulations with real populations)_.
- Developer _(I create tools that use OpenFisca-France-Data)_.

**Comment by benjello** [comment]
@sandcha @MattiSG : pourrait-on filer les autorisations qui vont bien à @benoit-cty ou corriger ce problème si ce n'est pas envisageable. Merci !

**Comment by MattiSG** [comment]
Je vois que @sandcha a rajouté la clé `SHA256:ZyOhRLaUiETL+JRVSZVngWV78YJwoFFVJP14deviiPs` le 24 avril 2021, et que les [déploiements précédents](https://app.circleci.com/pipelines/github/openfisca/openfisca-france-data/328/workflows/6acfa324-1731-4325-b213-62e302dc720d/jobs/775) ont également échoué.

Je remarque que dans #199, qui a été mergée, il n'y a pas de changement de numéro de version, et que l'étape qui bloque est celle de la modification du numéro de version.

Avant de créer une clé SSH avec un droit d'écriture, pourriez-vous confirmer que le processus de déploiement attendu ici est le même que dans OF-France ? 🙂 S'il n'y a pas de mécanisme de versionnement similaire, le plus simple est peut-être juste de supprimer l'étape de publication des tags, car il y aura dans tous les cas un conflit sinon.

**Comment by benjello** [comment]
> Je remarque que dans #199, qui a été mergée, il n'y a pas de changement de numéro de version, et que l'étape qui bloque est celle de la modification du numéro de version.

C'est un merge opportuniste d'une typo rajoutée car de tout façon le déploiement ne fonctionnait pas.

> Avant de créer une clé SSH avec un droit d'écriture, pourriez-vous confirmer que le processus de déploiement attendu ici est  le même que dans OF-France ? slightly_smiling_face S'il n'y a pas de mécanisme de versionnement similaire, le plus simple est peut-être juste de supprimer l'étape de publication des tags, car il y aura dans tous les cas un conflit sinon.

Oui c'est le même genre de déploiement qui est visé.

**Comment by MattiSG** [comment]
Merci pour ces informations @benjello !

Je vois que l'équipe openfisca/france-contrib a bien accès en écriture à ce dépôt, et que @openfisca-bot est dans cette équipe. J'en conclus que la clé SSH de @openfisca-bot n'a simplement pas été ajoutée au processus de déploiement CircleCI.

@sandcha as-tu accès à cette clé ? Si oui, peux-tu l'ajouter dans CircleCI ? 🙂

**Comment by sandcha** [comment]
Corrigé. 

Vous pouvez le voir sur [ce build](https://app.circleci.com/pipelines/github/openfisca/openfisca-france-data/338/workflows/5852714c-8a8e-40a3-8875-f97d6a43c4ec) qui m'a semblé être le dernier à versionner avant la correction de typo. 
La branche `master` actuelle (0.18 + correction de typo) ne nécessitait pas de bump et là, [la publication n'a pas eu lieu](https://app.circleci.com/pipelines/github/openfisca/openfisca-france-data/340/workflows/74e3f81b-7dae-49f2-878a-fc875170b49b/jobs/822), comme souhaité (pas de bump = pas de contenu à tagger).
> Néanmoins, nous pourrions améliorer le script pour qu'il ne s'achève plus avec l'erreur suivante et que le bilan du workflow soit vert : 
   HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
   File already exists. See https://pypi.org/help/#file-name-reuse for more information.

La correction appliquée a été de reprendre la même clef ssh publique en lui donnant cette fois-ci les droits en écriture sur GitHub (cf. [settings](https://github.com/openfisca/openfisca-france-data/settings/keys) ; elle avait été générée [pour débloquer le checkout](https://github.com/openfisca/openfisca-france-data/pull/192#issuecomment-818678857), d'où des droits passés en lecture seule).

Nous pouvons core cette issue si ça te semble bon @benjello.

**Comment by benjello** [comment]
Thanks @sandcha

**Comment by MattiSG** [comment]
Merci @sandcha ! 🙏
