### ISSUE TITLE
Echec de la publication en paquet conda

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france-data#230]
Hi there!

I really enjoy OpenFisca-France-Data, but I recently encountered an issue. cc @sylvainipp @benjello 

> N'étant pas au clair sur la langue par défaut de ce dépôt et la discussion ayant commencé en français dans la PR #229, je poursuis dans la même langue. 😊 

### Here is what I did:

La PR #229 a été mergée.

### Here is what I expected to happen:

Que la CI sur `master` s'achève sans erreur et en particulier que le paquet de la librairie produite par ce dépôt soit publié sur `conda`.

### Here is what actually happened:

En CI, l'étape `Download artifact`du job `publish-to-conda` indique [Error: no artifacts found](https://github.com/openfisca/openfisca-france-data/actions/runs/5677926588/job/15387317038#step:6:30).

### Here is data (or links to it) that can help you understand or reproduce this issue:

[La dernière version intégrée est la 2.0.0](https://github.com/openfisca/openfisca-france-data/blob/master/CHANGELOG.md#200-229) mais la [dernière version de paquet conda publiée](https://anaconda.org/search?q=openfisca-france-data) au 27.07.2023 est la `0.23.1`.

Le paquet conda est utilisé pour les calculs sur CASD. L'enjeux est en partie décrit ici : https://github.com/openfisca/openfisca-france-data/pull/229#issuecomment-1653206001

## Context

I identify more as a:

- Developer _(I create tools that use OpenFisca-France-Data)_.
- LexImpact _(I model reforms to make them exist)_.

**Comment by sandcha** [comment]
Le paquet conda est [construit à partir des sources du dépôt](https://github.com/openfisca/openfisca-france-data/blob/31ef285f89a1013870d029583d11dd2e1a6ed750/.conda/meta.yaml#L13-L14). Le problème n'est donc pas lié à PyPi (ou une désynchronisation éventuelle PyPi/CI de build conda).

**Comment by sandcha** [comment]
La différence de build vient du fait qu'on n'a pas le même nom pour un workflow trigger par le push ou par la PR : https://github.com/openfisca/openfisca-france-data/pull/229/checks (cf. les écarts de SHA entre workflow # 143 et # 144)

**Comment by benoit-cty** [comment]
Merci pour l'investigation !
Dans les logs de la CI du merge sur master il y a :
```
==> (not found) Artifact: conda-build-2.0.0-f3db7af65f140fbe42bba9f98e64a623a9b3819e  ⬅️ SHA du seul commit de la PR #229 : https://github.com/openfisca/openfisca-france-data/pull/229/commits/f3db7af65f140fbe42bba9f98e64a623a9b3819e
==> Found the following artifacts instead:
	==> (found) Artifact: conda-build-2.0.0-a81bda42026580568f4dce992dcda15b462432c6 ⬅️ Construit par la PR.
```

Pourtant dans https://github.com/openfisca/openfisca-france-data/actions/runs/5666636716/job/15353979575?pr=229#step:7:26 on lit:
```
Artifact conda-build-2.0.0-f3db7af65f140fbe42bba9f98e64a623a9b3819e has been successfully uploaded!
```

Donc il n'arrive pas à retrouver l’artefact pourtant bien uploadé. A la place il dit trouver  ` conda-build-2.0.0-a81bda42026580568f4dce992dcda15b462432c6` qui pourtant ne correspond à aucun commit :
```
$ git show a81bda42026580568f4dce992dcda15b462432c6
fatal: bad object a81bda42026580568f4dce992dcda15b462432c6
```

On peut utiliser la CLI de Github pour voir les artefacts :
```
gh api   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /repos/openfisca/openfisca-france-data/actions/artifacts
```

```json
{
  "total_count": 40,
  "artifacts": [
    {
      "id": 825600475,
      "node_id": "MDg6QXJ0aWZhY3Q4MjU2MDA0NzU=",
      "name": "conda-build-2.0.0-a81bda42026580568f4dce992dcda15b462432c6",
      "size_in_bytes": 329098,
      "url": "https://api.github.com/repos/openfisca/openfisca-france-data/actions/artifacts/825600475",
      "archive_download_url": "https://api.github.com/repos/openfisca/openfisca-france-data/actions/artifacts/825600475/zip",
      "expired": false,
      "created_at": "2023-07-26T09:57:44Z",
      "updated_at": "2023-07-26T09:57:46Z",
      "expires_at": "2023-08-25T09:40:17Z",
      "workflow_run": {
        "id": 5666704139,
        "repository_id": 18373026,
        "head_repository_id": 18373026,
        "head_branch": "MAJ_python",
        "head_sha": "f3db7af65f140fbe42bba9f98e64a623a9b3819e"
      }
    },
    {
      "id": 825561814,
      "node_id": "MDg6QXJ0aWZhY3Q4MjU1NjE4MTQ=",
      "name": "conda-build-2.0.0-f3db7af65f140fbe42bba9f98e64a623a9b3819e",
      "size_in_bytes": 328991,
      "url": "https://api.github.com/repos/openfisca/openfisca-france-data/actions/artifacts/825561814",
      "archive_download_url": "https://api.github.com/repos/openfisca/openfisca-france-data/actions/artifacts/825561814/zip",
      "expired": false,
      "created_at": "2023-07-26T09:37:33Z",
      "updated_at": "2023-07-26T09:37:34Z",
      "expires_at": "2023-08-25T09:20:10Z",
      "workflow_run": {
        "id": 5666636716,
        "repository_id": 18373026,
        "head_repository_id": 18373026,
        "head_branch": "MAJ_python",
        "head_sha": "f3db7af65f140fbe42bba9f98e64a623a9b3819e"
      }
    },
...
  ]
}
```
Donc l'artefact existe bien mais il y a deux artefacts pour le même commit, c'est peut-être ça qui empêche sa récupération ?

**Comment by benoit-cty** [comment]
Sur OpenFisca France nous utilisons le même processus de build et le phénomène se produit aussi, par exemple pour le commit `a1c10f882a03182ea7a41a3520dbd5cc9e5878c7` il y a eu deux artefacts de générés  :
```json
 {
      "id": 829503315,
      "node_id": "MDg6QXJ0aWZhY3Q4Mjk1MDMzMTU=",
      "name": "conda-build-150.0.1-a1c10f882a03182ea7a41a3520dbd5cc9e5878c7",
      "size_in_bytes": 3058041,
      "url": "https://api.github.com/repos/openfisca/openfisca-france/actions/artifacts/829503315",
      "archive_download_url": "https://api.github.com/repos/openfisca/openfisca-france/actions/artifacts/829503315/zip",
      "expired": false,
      "created_at": "2023-07-27T23:14:56Z",
      "updated_at": "2023-07-27T23:14:57Z",
      "expires_at": "2023-08-26T22:34:52Z",
      "workflow_run": {
        "id": 5685570938,
        "repository_id": 15510233,
        "head_repository_id": 15510233,
        "head_branch": "parameter_marche_travail.primes_exceptionnelles.prime_partage_valeur.plafond_exoneration_avec_accord_interessement_a3b617df",
        "head_sha": "a1c10f882a03182ea7a41a3520dbd5cc9e5878c7"
      }
    },
    {
      "id": 829499354,
      "node_id": "MDg6QXJ0aWZhY3Q4Mjk0OTkzNTQ=",
      "name": "conda-build-150.0.1-a6e8d0ce1606ebe5e426f346fae7c3625a6c9168",
      "size_in_bytes": 3085313,
      "url": "https://api.github.com/repos/openfisca/openfisca-france/actions/artifacts/829499354",
      "archive_download_url": "https://api.github.com/repos/openfisca/openfisca-france/actions/artifacts/829499354/zip",
      "expired": false,
      "created_at": "2023-07-27T23:11:40Z",
      "updated_at": "2023-07-27T23:11:41Z",
      "expires_at": "2023-08-26T22:32:54Z",
      "workflow_run": {
        "id": 5685570989,
        "repository_id": 15510233,
        "head_repository_id": 15510233,
        "head_branch": "parameter_marche_travail.primes_exceptionnelles.prime_partage_valeur.plafond_exoneration_avec_accord_interessement_a3b617df",
        "head_sha": "a1c10f882a03182ea7a41a3520dbd5cc9e5878c7"
      }
```
Par ce workflow : https://github.com/openfisca/openfisca-france/actions/runs/5685570938 _Triggered via push_

**Comment by benoit-cty** [comment]
C'était bien le problème, j'ai ajouté l'option [`event: push`](https://github.com/openfisca/openfisca-france-data/pull/232/files#diff-126bf89616b7daa3d14ebc882ad18666aaf1c3dae888c4ba306a66ec80758bc1R263) et le workflow c'est bien passé : https://github.com/openfisca/openfisca-france-data/actions/runs/5716879276

Mais il va falloir faire cela sur tous les workflows OpenFisca...
